In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("Resources/state_M2017_dl.csv")
df

,AREA,ST,STATE,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC_Q,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,1,AL,Alabama,00-0000,All Occupations,total,"1,922,570",0.4,1000.000,1.00,...,15.77,25.01,37.83,"17,770","21,740","32,800","52,020","78,690",NaN,NaN
1,1,AL,Alabama,11-0000,Management Occupations,major,"69,950",1.0,36.385,0.71,...,46.63,64.12,90.80,"52,130","70,130","96,980","133,360","188,860",NaN,NaN
2,1,AL,Alabama,11-1011,Chief Executives,detailed,"1,120",6.0,0.585,0.40,...,94.45,#,#,"84,520","125,290","196,460",#,#,NaN,NaN
3,1,AL,Alabama,11-1021,General and Operations Managers,detailed,"27,150",1.6,14.123,0.91,...,49.19,71.09,#,"54,040","72,610","102,320","147,860",#,NaN,NaN
4,1,AL,Alabama,11-1031,Legislators,detailed,"1,100",12.0,0.572,1.59,...,*,*,*,"16,310","17,280","18,910","24,630","47,510",True,NaN
5,1,AL,Alabama,11-2011,Advertising and Promotions Managers,detailed,60,17.9,0.029,0.15,...,*,*,*,*,*,*,*,*,NaN,NaN
6,1,AL,Alabama,11-2021,Marketing Managers,detailed,540,6.4,0.280,0.18,...,53.05,74.94,97.48,"59,910","76,200","110,350","155,860","202,750",NaN,NaN
7,1,AL,Alabama,11-2022,Sales Managers,detailed,"2,220",5.7,1.157,0.44,...,53.69,74.02,99.08,"61,630","83,850","111,680","153,960","206,080",NaN,NaN
8,1,AL,Alabama,11-2031,Public Relations and Fundraising Managers,detailed,430,7.6,0.222,0.47,...,39.62,51.22,74.08,"55,270","66,100","82,400","106,530","154,080",NaN,NaN
9,1,AL,Alabama,11-3011,Administrative Services Managers,detailed,590,8.6,0.309,0.16,...,44.50,57.01,70.56,"60,740","73,510","92,550","118,570","146,770",NaN,NaN
10,1,AL,Alabama,11-3021,Computer and Information Systems Managers,detailed,"3,120",5.9,1.624,0.63,...,56.24,71.68,88.92,"66,710","90,290","116,990","149,100","184,950",NaN,NaN
11,1,AL,Alabama,11-3031,Financial Managers,detailed,"5,200",2.4,2.703,0.68,...,56.88,75.23,98.81,"69,460","90,160","118,310","156,490","205,520",NaN,NaN
12,1,AL,Alabama,11-3051,Industrial Production Managers,detailed,"3,240",3.3,1.684,1.40,...,46.30,58.57,73.66,"62,050","76,020","96,300","121,820","153,210",NaN,NaN
13,1,AL,Alabama,11-3061,Purchasing Managers,detailed,900,2.5,0.468,0.95,...,53.25,61.58,72.43,"68,590","83,610","110,760","128,080","150,650",NaN,NaN
14,1,AL,Alabama,11-3071,"Transportation, Storage, and Distribution Mana...",detailed,750,13.0,0.389,0.47,...,40.04,51.90,65.84,"36,350","58,900","83,290","107,960","136,940",NaN,NaN
15,1,AL,Alabama,11-3111,Compensation and Benefits Managers,detailed,70,11.3,0.036,0.33,...,53.96,71.02,93.36,"77,140","90,350","112,230","147,730","194,190",NaN,NaN
16,1,AL,Alabama,11-3121,Human Resources Managers,detailed,"1,200",2.9,0.626,0.65,...,46.76,60.88,76.82,"59,650","74,020","97,260","126,630","159,790",NaN,NaN
17,1,AL,Alabama,11-3131,Training and Development Managers,detailed,140,8.6,0.072,0.30,...,53.42,66.21,93.22,"64,740","86,500","111,110","137,720","193,900",NaN,NaN
18,1,AL,Alabama,11-9021,Construction Managers,detailed,"2,780",5.5,1.445,0.78,...,39.92,50.12,67.59,"54,090","65,990","83,030","104,240","140,580",NaN,NaN
19,1,AL,Alabama,11-9031,"Education Administrators, Preschool and Childc...",detailed,170,27.0,0.090,0.26,...,16.36,21.16,29.08,"23,400","28,710","34,040","44,020","60,490",NaN,NaN
20,1,AL,Alabama,11-9032,"Education Administrators, Elementary and Secon...",detailed,"3,430",4.1,1.783,1.02,...,*,*,*,"59,060","68,810","79,880","94,100","103,880",True,NaN
21,1,AL,Alabama,11-9033,"Education Administrators, Postsecondary",detailed,"2,430",2.1,1.263,1.27,...,43.13,60.03,86.32,"55,500","67,840","89,710","124,870","179,530",NaN,NaN
22,1,AL,Alabama,11-9039,"Education Administrators, All Other",detailed,590,3.2,0.305,1.20,...,45.19,53.63,61.76,"55,780","78,690","93,990","111,560","128,450",NaN,NaN
23,1,AL,Alabama,11-9041,Architectural and Engineering Managers,detailed,"2,450",3.6,1.273,1.01,...,64.58,77.65,93.31,"89,210","112,790","134,330","161,510","194,080",NaN,NaN
24,1,AL,Alabama,11-9051,Food Service Managers,detailed,"2,180",5.7,1.136,0.78,...,28.04,36.57,49.84,"38,990","45,770","58,320","76,060","103,660",NaN,NaN
25,1,AL,Alabama,11-9061,Funeral Service Managers,detailed,140,16.3,0.074,1.26,...,38.72,48.51,61.56,"28,970","50,190","80,540","100,900","128,050",NaN,NaN
26,1,AL,Alabama,11-9081,Lodging Managers,detailed,530,9.5,0.276,1.07,...,24.22,29.58,36.09,"31,560","38,200","50,380","61,530","75,070",NaN,NaN
27,1,AL,Alabama,11-9111,Medical and Health Services Managers,detailed,"2,810",2.2,1.461,0.60,...,44.27,58.15,76.35,"58,020","72,770","92,070","120,960","158,810",NaN,NaN
28,1,AL,Alabama,11-9121,Natural Sciences Managers,detailed,140,9.2,0.073,0.18,...,49.71,58.50,70.73,"80,620","91,530","103,390","121,680","147,120",NaN,NaN
29,1,AL,Alabama,11-9131,Postmasters and Mail Superintendents,detailed,280,0.0,0.146,1.49,...,36.84,40.21,44.39,"65,580","69,690","76,620","83,630","92,330",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36962,78,VI,Virgin Islands,47-2141,"Painters, Construction and Maintenance",detailed,50,17.9,1.222,0.79,...,16.81,18.97,22.53,"24,530","29,250","34,960","39,450","46,860",NaN,NaN
36963,78,VI,Virgin Islands,47-2211,Sheet Metal Workers,detailed,**,**,**,**,...,18.40,21.94,24.57,"28,530","33,220","38,260","45,640","51,110",NaN,NaN
36964,78,VI,Virgin Islands,49-0000,"Installation, Maintenance, and Repair Occupations",major,"1,510",7.3,40.205,1.04,...,16.11,21.30,27.86,"21,970","26,670","33,510","44,300","57,950",NaN,NaN
36965,78,VI,Virgin Islands,49-1011,"First-Line Supervisors of Mechanics, Installer...",detailed,150,16.5,4.105,1.27,...,22.39,25.96,36.24,"34,400","41,080","46,560","54,010","75,380",NaN,NaN
36966,78,VI,Virgin Islands,49-2022,Telecommunications Equipment Installers and Re...,detailed,30,41.7,0.835,0.51,...,25.10,34.15,37.82,"33,260","37,510","52,210","71,030","78,660",NaN,NaN
36967,78,VI,Virgin Islands,49-3023,Automotive Service Technicians and Mechanics,detailed,180,15.0,4.881,1.09,...,15.10,18.28,23.16,"21,840","26,910","31,410","38,010","48,160",NaN,NaN
36968,78,VI,Virgin Islands,49-3031,Bus and Truck Mechanics and Diesel Engine Spec...,detailed,40,25.4,0.998,0.55,...,21.61,24.25,29.83,"26,070","36,590","44,960","50,440","62,050",NaN,NaN
36969,78,VI,Virgin Islands,49-3051,Motorboat Mechanics and Service Technicians,detailed,40,43.7,1.184,7.98,...,17.16,22.75,29.68,"27,030","29,350","35,690","47,320","61,730",NaN,NaN
36970,78,VI,Virgin Islands,49-9021,"Heating, Air Conditioning, and Refrigeration M...",detailed,100,12.9,2.603,1.21,...,16.70,22.07,29.97,"24,580","28,300","34,730","45,900","62,340",NaN,NaN
36971,78,VI,Virgin Islands,49-9071,"Maintenance and Repair Workers, General",detailed,720,11.7,19.248,2.03,...,14.34,18.01,22.28,"21,210","24,790","29,830","37,470","46,350",NaN,NaN
36972,78,VI,Virgin Islands,49-9099,"Installation, Maintenance, and Repair Workers,...",detailed,40,20.7,1.139,1.06,...,19.52,26.87,29.09,"18,620","20,030","40,610","55,890","60,510",NaN,NaN
36973,78,VI,Virgin Islands,51-0000,Production Occupations,major,840,8.2,22.534,0.36,...,16.00,23.09,29.52,"19,720","25,650","33,280","48,030","61,390",NaN,NaN
36974,78,VI,Virgin Islands,51-1011,First-Line Supervisors of Production and Opera...,detailed,120,13.7,3.174,0.74,...,24.66,33.28,41.60,"30,490","36,480","51,300","69,220","86,520",NaN,NaN
36975,78,VI,Virgin Islands,51-3021,Butchers and Meat Cutters,detailed,60,18.1,1.475,1.60,...,14.00,17.67,22.86,"18,890","23,260","29,130","36,750","47,550",NaN,NaN
36976,78,VI,Virgin Islands,51-6011,Laundry and Dry-Cleaning Workers,detailed,170,14.7,4.404,3.00,...,11.37,13.71,15.01,"18,450","19,720","23,650","28,530","31,230",NaN,NaN
36977,78,VI,Virgin Islands,51-9071,Jewelers and Precious Stone and Metal Workers,detailed,40,8.3,1.115,6.18,...,19.83,26.66,29.41,"21,830","25,430","41,240","55,460","61,180",NaN,NaN
36978,78,VI,Virgin Islands,53-0000,Transportation and Material Moving Occupations,major,"2,110",7.5,56.148,0.80,...,12.68,17.40,23.11,"18,800","20,560","26,370","36,180","48,070",NaN,NaN
36979,78,VI,Virgin Islands,53-1048,First-Line Supervisors of Transportation and M...,detailed,60,25.1,1.574,0.57,...,19.70,24.18,38.40,"29,170","34,110","40,970","50,290","79,870",NaN,NaN
36980,78,VI,Virgin Islands,53-3022,"Bus Drivers, School or Special Client",detailed,80,38.8,2.094,0.59,...,12.38,14.25,16.36,"19,950","22,030","25,760","29,640","34,030",NaN,NaN
36981,78,VI,Virgin Islands,53-3031,Driver/Sales Workers,detailed,120,49.8,3.318,1.11,...,9.69,13.85,21.75,"18,150","18,890","20,160","28,810","45,240",NaN,NaN
36982,78,VI,Virgin Islands,53-3032,Heavy and Tractor-Trailer Truck Drivers,detailed,260,32.5,6.901,0.56,...,16.09,18.89,22.82,"21,610","24,670","33,480","39,280","47,470",NaN,NaN
36983,78,VI,Virgin Islands,53-3033,Light Truck or Delivery Services Drivers,detailed,200,22.8,5.449,0.89,...,12.33,15.68,18.74,"19,340","21,440","25,650","32,620","38,980",NaN,NaN
36984,78,VI,Virgin Islands,53-5011,Sailors and Marine Oilers,detailed,60,14.3,1.544,7.12,...,13.94,15.19,17.97,"21,890","26,420","29,000","31,600","37,380",NaN,NaN
36985,78,VI,Virgin Islands,53-5021,"Captains, Mates, and Pilots of Water Vessels",detailed,190,20.8,5.196,20.70,...,20.94,24.40,36.17,"26,360","30,690","43,560","50,760","75,230",NaN,NaN
36986,78,VI,Virgin Islands,53-6031,Automotive and Watercraft Service Attendants,detailed,70,15.9,1.790,2.15,...,9.95,12.03,13.93,"18,190","18,960","20,700","25,020","28,970",NaN,NaN
36987,78,VI,Virgin Islands,53-7051,Industrial Truck and Tractor Operators,detailed,50,25.3,1.422,0.36,...,15.78,18.69,30.90,"22,060","25,600","32,830","38,880","64,270",NaN,NaN
36988,78,VI,Virgin Islands,53-7061,Cleaners of Vehicles and Equipment,detailed,30,17.8,0.856,0.33,...,9.29,9.69,11.96,"18,010","18,500","19,320","20,160","24,870",NaN,NaN
36989,78,VI,Virgin Islands,53-7062,"Laborers and Freight, Stock, and Material Move...",detailed,500,13.2,13.313,0.70,...,10.91,12.66,15.90,"18,430","19,660","22,690","26,340","33,070",NaN,NaN
36990,78,VI,Virgin Islands,53-7064,"Packers and Packagers, Hand",detailed,140,23.8,3.801,0.77,...,9.20,9.55,10.15,"17,970","18,410","19,140","19,860","21,120",NaN,NaN
36991,78,VI,Virgin Islands,53-7199,"Material Moving Workers, All Other",detailed,50,26.0,1.270,6.96,...,22.59,26.62,33.12,"35,570","41,200","46,980","55,370","68,890",NaN,NaN

In [13]:
df.columns

Index(['AREA', 'ST', 'STATE', 'OCC_CODE', 'OCC_TITLE', 'OCC_GROUP', 'TOT_EMP',
       'EMP_PRSE', 'JOBS_1000', 'LOC_Q', 'H_MEAN', 'A_MEAN', 'MEAN_PRSE',
       'H_PCT10', 'H_PCT25', 'H_MEDIAN', 'H_PCT75', 'H_PCT90', 'A_PCT10',
       'A_PCT25', 'A_MEDIAN', 'A_PCT75', 'A_PCT90', 'ANNUAL', 'HOURLY'],
      dtype='object')

In [14]:
df.count()

AREA         36992
ST           36992
STATE        36992
OCC_CODE     36992
OCC_TITLE    36992
OCC_GROUP    36992
TOT_EMP      36992
EMP_PRSE     36992
JOBS_1000    36992
LOC_Q        36992
H_MEAN       36992
A_MEAN       36992
MEAN_PRSE    36992
H_PCT10      36992
H_PCT25      36992
H_MEDIAN     36992
H_PCT75      36992
H_PCT90      36992
A_PCT10      36992
A_PCT25      36992
A_MEDIAN     36992
A_PCT75      36992
A_PCT90      36992
ANNUAL        2589
HOURLY         129
dtype: int64

In [15]:
df["OCC_TITLE"].value_counts()

Computer Systems Analysts                                                                                           54
Cashiers                                                                                                            54
First-Line Supervisors of Personal Service Workers                                                                  54
First-Line Supervisors of Mechanics, Installers, and Repairers                                                      54
Executive Secretaries and Executive Administrative Assistants                                                       54
Human Resources Specialists                                                                                         54
Tellers                                                                                                             54
First-Line Supervisors of Transportation and Material Moving Workers, Except Aircraft Cargo Handling Supervisors    54
Life, Physical, and Social Science Occupations                                                                      54
Elementary School Teachers, Except Special Education                                                                54
Bus Drivers, School or Special Client                                                                               54
Dining Room and Cafeteria Attendants and Bartender Helpers                                                          54
Counter and Rental Clerks                                                                                           54
Sales and Related Occupations                                                                                       54
Cleaners of Vehicles and Equipment                                                                                  54
Shipping, Receiving, and Traffic Clerks                                                                             54
Office and Administrative Support Occupations                                                                       54
First-Line Supervisors of Food Preparation and Serving Workers                                                      54
Cooks, Restaurant                                                                                                   54
Transportation and Material Moving Occupations                                                                      54
Counter Attendants, Cafeteria, Food Concession, and Coffee Shop                                                     54
Heating, Air Conditioning, and Refrigeration Mechanics and Installers                                               54
Bus and Truck Mechanics and Diesel Engine Specialists                                                               54
Pharmacists                                                                                                         54
Bill and Account Collectors                                                                                         54
Office Clerks, General                                                                                              54
All Occupations                                                                                                     54
Medical Secretaries                                                                                                 54
Electricians                                                                                                        54
Automotive and Watercraft Service Attendants                                                                        54
                                                                                                                    ..
Political Scientists                                                                                                14
Mining Machine Operators, All Other                                                                                 14
Logging Workers, All Other                                                                                          13
Watch Repairers                                                                                                     12
Subway and Streetcar Operators                                                                                      12
Motorboat Operators                                                                                                 12
Animal Breeders                                                                                                     12
Geographers                                                                                                         12
Makeup Artists, Theatrical and Performance                                                                          12
Loading Machine Operators, Underground Mining                                                                       11
Terrazzo Workers and Finishers                                                                                      11
Transit and Railroad Police                                                                                         10
Shoe Machine Operators and Tenders                                                                                  10
Forest Fire Inspectors and Prevention Specialists                                                                   10
Astronomers                                                                                                          9
Refractory Materials Repairers, Except Brickmasons                                                                   9
Patternmakers, Wood                                                                                                  9
Rail Transportation Workers, All Other                                                                               7
Roof Bolters, Mining                                                                                                 6
Radio Operators                                                                                                      6
Industrial-Organizational Psychologists                                                                              6
Mine Shuttle Car Operators                                                                                           5
Nuclear Power Reactor Operators                                                                                      4
Timing Device Assemblers and Adjusters                                                                               3
Fishers and Related Fishing Workers                                                                                  3
Fabric Menders, Except Garment                                                                                       3
Model Makers, Wood                                                                                                   2
Cooks, Private Household                                                                                             2
Farm Labor Contractors                                                                                               2
Prosthodontists                                                                                                      1
Name: OCC_TITLE, Length: 831, dtype: int64

In [16]:
new_df = df[df["OCC_CODE"].str.contains("^15")]
new_df

,AREA,ST,STATE,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC_Q,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
63,1,AL,Alabama,15-0000,Computer and Mathematical Occupations,major,"39,760",2.3,20.680,0.69,...,37.30,49.05,61.78,"42,150","56,630","77,590","102,020","128,500",NaN,NaN
64,1,AL,Alabama,15-1121,Computer Systems Analysts,detailed,"4,010",9.4,2.084,0.51,...,37.89,46.97,56.72,"53,510","64,190","78,800","97,710","117,970",NaN,NaN
65,1,AL,Alabama,15-1122,Information Security Analysts,detailed,"1,100",7.8,0.573,0.78,...,42.15,53.51,61.89,"54,360","66,790","87,660","111,290","128,720",NaN,NaN
66,1,AL,Alabama,15-1131,Computer Programmers,detailed,"7,420",4.6,3.858,2.22,...,40.49,51.08,65.95,"47,700","62,640","84,230","106,240","137,180",NaN,NaN
67,1,AL,Alabama,15-1132,"Software Developers, Applications",detailed,"5,540",5.5,2.883,0.48,...,43.00,55.35,66.43,"52,150","67,410","89,440","115,120","138,180",NaN,NaN
68,1,AL,Alabama,15-1133,"Software Developers, Systems Software",detailed,"3,720",8.7,1.933,0.70,...,47.04,60.66,74.90,"65,460","77,410","97,840","126,180","155,800",NaN,NaN
69,1,AL,Alabama,15-1134,Web Developers,detailed,600,10.8,0.313,0.35,...,26.36,34.82,45.73,"32,750","43,500","54,840","72,430","95,130",NaN,NaN
70,1,AL,Alabama,15-1141,Database Administrators,detailed,"1,910",9.0,0.991,1.24,...,39.08,48.48,58.82,"49,070","61,730","81,290","100,830","122,340",NaN,NaN
71,1,AL,Alabama,15-1142,Network and Computer Systems Administrators,detailed,"4,230",3.3,2.201,0.84,...,33.95,43.47,53.22,"44,990","55,980","70,610","90,430","110,700",NaN,NaN
72,1,AL,Alabama,15-1143,Computer Network Architects,detailed,830,7.7,0.429,0.39,...,48.26,59.21,69.98,"65,500","79,490","100,380","123,160","145,560",NaN,NaN
73,1,AL,Alabama,15-1151,Computer User Support Specialists,detailed,"5,930",6.0,3.084,0.72,...,22.10,28.14,35.47,"29,570","36,250","45,980","58,540","73,770",NaN,NaN
74,1,AL,Alabama,15-1152,Computer Network Support Specialists,detailed,"1,000",7.7,0.523,0.40,...,29.24,36.47,44.38,"37,400","46,960","60,810","75,860","92,300",NaN,NaN
75,1,AL,Alabama,15-1199,"Computer Occupations, All Other",detailed,"1,810",3.9,0.940,0.42,...,41.64,49.51,56.88,"58,120","72,160","86,610","102,980","118,310",NaN,NaN
76,1,AL,Alabama,15-2011,Actuaries,detailed,80,18.5,0.042,0.31,...,39.25,56.05,71.15,"51,880","62,010","81,650","116,580","147,990",NaN,NaN
77,1,AL,Alabama,15-2031,Operations Research Analysts,detailed,670,9.5,0.350,0.47,...,44.85,57.24,69.89,"48,080","63,570","93,300","119,070","145,370",NaN,NaN
78,1,AL,Alabama,15-2041,Statisticians,detailed,180,4.0,0.093,0.36,...,29.63,36.85,45.10,"40,700","48,290","61,630","76,650","93,820",NaN,NaN
784,2,AK,Alaska,15-0000,Computer and Mathematical Occupations,major,"5,450",6.8,17.124,0.57,...,36.92,47.13,59.75,"42,890","56,840","76,800","98,040","124,290",NaN,NaN
785,2,AK,Alaska,15-1121,Computer Systems Analysts,detailed,860,16.2,2.695,0.66,...,35.41,45.16,51.72,"35,280","47,740","73,660","93,930","107,580",NaN,NaN
786,2,AK,Alaska,15-1122,Information Security Analysts,detailed,70,35.8,0.230,0.31,...,45.34,52.12,72.43,"49,960","80,770","94,310","108,400","150,660",NaN,NaN
787,2,AK,Alaska,15-1131,Computer Programmers,detailed,600,8.2,1.877,1.08,...,41.15,49.15,61.93,"53,120","67,600","85,590","102,230","128,820",NaN,NaN
788,2,AK,Alaska,15-1132,"Software Developers, Applications",detailed,340,23.5,1.056,0.18,...,*,*,*,*,*,*,*,*,NaN,NaN
789,2,AK,Alaska,15-1133,"Software Developers, Systems Software",detailed,130,41.1,0.395,0.14,...,*,*,*,*,*,*,*,*,NaN,NaN
790,2,AK,Alaska,15-1134,Web Developers,detailed,190,18.7,0.603,0.68,...,25.90,36.09,44.84,"35,390","42,080","53,860","75,070","93,270",NaN,NaN
791,2,AK,Alaska,15-1141,Database Administrators,detailed,200,9.7,0.635,0.80,...,37.12,48.22,59.75,"44,310","58,200","77,210","100,300","124,290",NaN,NaN
792,2,AK,Alaska,15-1142,Network and Computer Systems Administrators,detailed,"1,020",15.8,3.213,1.22,...,38.45,47.49,60.13,"54,270","63,780","79,970","98,790","125,080",NaN,NaN
793,2,AK,Alaska,15-1143,Computer Network Architects,detailed,90,30.8,0.281,0.25,...,48.50,58.83,75.94,"37,500","84,560","100,880","122,360","157,950",NaN,NaN
794,2,AK,Alaska,15-1151,Computer User Support Specialists,detailed,830,6.7,2.623,0.61,...,27.51,33.89,42.11,"39,010","46,550","57,220","70,480","87,580",NaN,NaN
795,2,AK,Alaska,15-1152,Computer Network Support Specialists,detailed,320,10.8,1.012,0.77,...,26.62,33.05,43.80,"40,180","45,940","55,370","68,740","91,100",NaN,NaN
796,2,AK,Alaska,15-1199,"Computer Occupations, All Other",detailed,540,6.8,1.703,0.77,...,44.10,51.00,57.74,"67,960","77,930","91,730","106,090","120,100",NaN,NaN
797,2,AK,Alaska,15-2031,Operations Research Analysts,detailed,120,14.1,0.364,0.49,...,35.79,44.89,70.47,"43,140","57,980","74,450","93,360","146,580",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35489,56,WY,Wyoming,15-1151,Computer User Support Specialists,detailed,590,4.3,2.190,0.51,...,22.67,27.65,32.20,"30,700","38,490","47,150","57,520","66,980",NaN,NaN
35490,56,WY,Wyoming,15-1152,Computer Network Support Specialists,detailed,240,4.6,0.902,0.69,...,27.88,34.06,38.86,"33,850","44,800","57,980","70,850","80,830",NaN,NaN
35491,56,WY,Wyoming,15-1199,"Computer Occupations, All Other",detailed,140,1.1,0.513,0.23,...,33.65,40.86,48.13,"55,050","63,710","69,990","84,990","100,120",NaN,NaN
36009,66,GU,Guam,15-0000,Computer and Mathematical Occupations,major,580,2.2,9.468,0.32,...,22.06,31.25,41.26,"26,510","34,340","45,890","65,000","85,830",NaN,NaN
36010,66,GU,Guam,15-1121,Computer Systems Analysts,detailed,70,4.2,1.107,0.27,...,22.57,26.46,30.57,"29,910","40,860","46,950","55,030","63,580",NaN,NaN
36011,66,GU,Guam,15-1142,Network and Computer Systems Administrators,detailed,80,10.6,1.307,0.50,...,25.07,33.34,42.00,"35,740","42,120","52,150","69,340","87,370",NaN,NaN
36012,66,GU,Guam,15-1151,Computer User Support Specialists,detailed,130,3.7,2.168,0.50,...,16.26,20.43,25.53,"21,630","25,940","33,830","42,500","53,100",NaN,NaN
36013,66,GU,Guam,15-1152,Computer Network Support Specialists,detailed,80,4.7,1.253,0.96,...,17.77,22.77,29.18,"25,890","29,390","36,960","47,360","60,700",NaN,NaN
36014,66,GU,Guam,15-1199,"Computer Occupations, All Other",detailed,100,0.0,1.616,0.73,...,38.76,42.75,48.13,"41,230","71,460","80,630","88,910","100,110",NaN,NaN
36282,72,PR,Puerto Rico,15-0000,Computer and Mathematical Occupations,major,"10,660",3.4,12.175,0.41,...,18.75,26.73,36.19,"19,910","27,480","39,000","55,590","75,280",NaN,NaN
36283,72,PR,Puerto Rico,15-1121,Computer Systems Analysts,detailed,"1,170",5.0,1.340,0.33,...,21.11,27.78,35.71,"19,390","29,560","43,900","57,780","74,270",NaN,NaN
36284,72,PR,Puerto Rico,15-1122,Information Security Analysts,detailed,310,23.0,0.350,0.47,...,20.82,24.13,32.15,"26,610","33,220","43,300","50,200","66,870",NaN,NaN
36285,72,PR,Puerto Rico,15-1131,Computer Programmers,detailed,"1,320",8.6,1.510,0.87,...,21.82,29.34,36.58,"23,800","32,740","45,380","61,030","76,080",NaN,NaN
36286,72,PR,Puerto Rico,15-1132,"Software Developers, Applications",detailed,260,11.8,0.301,0.05,...,26.26,34.88,43.76,"29,650","40,180","54,620","72,560","91,020",NaN,NaN
36287,72,PR,Puerto Rico,15-1133,"Software Developers, Systems Software",detailed,860,26.4,0.986,0.36,...,28.03,34.86,42.51,"37,660","46,330","58,310","72,500","88,420",NaN,NaN
36288,72,PR,Puerto Rico,15-1134,Web Developers,detailed,220,11.1,0.248,0.28,...,17.20,22.03,26.59,"21,880","27,280","35,780","45,830","55,300",NaN,NaN
36289,72,PR,Puerto Rico,15-1141,Database Administrators,detailed,410,6.9,0.472,0.59,...,22.59,28.75,35.62,"26,810","35,440","46,980","59,800","74,090",NaN,NaN
36290,72,PR,Puerto Rico,15-1142,Network and Computer Systems Administrators,detailed,940,6.8,1.074,0.41,...,20.66,28.38,36.36,"26,480","32,560","42,970","59,020","75,630",NaN,NaN
36291,72,PR,Puerto Rico,15-1143,Computer Network Architects,detailed,620,5.4,0.705,0.64,...,19.37,29.47,44.64,"33,150","35,820","40,290","61,290","92,860",NaN,NaN
36292,72,PR,Puerto Rico,15-1151,Computer User Support Specialists,detailed,"3,320",5.4,3.789,0.88,...,13.32,18.25,24.44,"17,570","20,950","27,710","37,960","50,840",NaN,NaN
36293,72,PR,Puerto Rico,15-1152,Computer Network Support Specialists,detailed,500,9.3,0.567,0.43,...,17.13,22.82,30.37,"20,730","26,340","35,630","47,470","63,170",NaN,NaN
36294,72,PR,Puerto Rico,15-1199,"Computer Occupations, All Other",detailed,370,20.8,0.419,0.19,...,33.22,42.75,49.03,"18,300","29,360","69,100","88,920","101,970",NaN,NaN
36295,72,PR,Puerto Rico,15-2011,Actuaries,detailed,30,2.9,0.039,0.29,...,27.26,33.88,41.72,"36,720","45,440","56,700","70,460","86,770",NaN,NaN
36296,72,PR,Puerto Rico,15-2031,Operations Research Analysts,detailed,80,9.0,0.092,0.12,...,24.51,41.23,47.61,"23,030","28,210","50,990","85,770","99,020",NaN,NaN
36297,72,PR,Puerto Rico,15-2041,Statisticians,detailed,230,4.8,0.267,1.04,...,17.00,19.32,26.61,"24,980","29,640","35,360","40,190","55,350",NaN,NaN
36838,78,VI,Virgin Islands,15-0000,Computer and Mathematical Occupations,major,350,5.6,9.403,0.31,...,23.87,30.34,40.55,"32,900","39,700","49,650","63,120","84,350",NaN,NaN
36839,78,VI,Virgin Islands,15-1121,Computer Systems Analysts,detailed,50,3.4,1.344,0.33,...,23.32,29.82,36.48,"34,610","40,670","48,510","62,030","75,870",NaN,NaN
36840,78,VI,Virgin Islands,15-1142,Network and Computer Systems Administrators,detailed,40,14.9,1.128,0.43,...,31.40,40.69,68.73,"46,860","55,560","65,320","84,630","142,960",NaN,NaN
36841,78,VI,Virgin Islands,15-1151,Computer User Support Specialists,detailed,100,18.8,2.670,0.62,...,19.23,23.87,29.21,"31,140","34,500","39,990","49,650","60,760",NaN,NaN
36842,78,VI,Virgin Islands,15-1152,Computer Network Support Specialists,detailed,50,17.7,1.203,0.92,...,21.33,25.12,29.26,"20,690","33,720","44,360","52,250","60,870",NaN,NaN

In [17]:
new_df.count()

AREA         892
ST           892
STATE        892
OCC_CODE     892
OCC_TITLE    892
OCC_GROUP    892
TOT_EMP      892
EMP_PRSE     892
JOBS_1000    892
LOC_Q        892
H_MEAN       892
A_MEAN       892
MEAN_PRSE    892
H_PCT10      892
H_PCT25      892
H_MEDIAN     892
H_PCT75      892
H_PCT90      892
A_PCT10      892
A_PCT25      892
A_MEDIAN     892
A_PCT75      892
A_PCT90      892
ANNUAL         0
HOURLY         0
dtype: int64